const test = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const ts = require('typescript');
const sodium = require('libsodium-wrappers-sumo');
function load(file, overrides = {}) {
  const code = ts.transpileModule(readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText;
  const module = { exports: {} };
  new Function('require', 'module', 'exports', code)(name => name in overrides ? overrides[name] : require(name), module, module.exports);
  return module.exports;
}

test('Zod 4 keeps transfer validation and error messages', () => {
  const { TransferZodSchema: schema } = load('src/schema/coins.ts');
  assert.deepEqual(schema.parse({ senderId: ' sender ', recipientId: ' recipient ', amount: 100 }), { senderId: 'sender', recipientId: 'recipient', amount: 100 });
  for (const amount of [undefined, '100', NaN, Infinity]) {
    const result = schema.safeParse({ senderId: 'sender', recipientId: 'recipient', amount });
    assert.equal(result.success, false);
    assert.equal(result.error.issues[0].message, 'Amount must be a number');
  }
  assert.equal(schema.safeParse({ senderId: 'sender', recipientId: 'recipient', amount: 99 }).error.issues[0].message, 'Minimum amount is 100 Coins');
});

test('libsodium upgrade preserves message-chain derivation and decryption', async () => {
  await sodium.ready;
  const { initSession, encryptMessage, decryptMessage } = load('src/lib/sodium/doubleRatchet.ts', { 'idb-keyval': {} });
  const b64 = bytes => sodium.to_base64(bytes, sodium.base64_variants.ORIGINAL);
  const chain = b64(new Uint8Array(32).fill(7));
  const sender = await initSession(b64(new Uint8Array(32).fill(9)));
  const recipient = await initSession(b64(new Uint8Array(32).fill(9)));
  sender.CKs_b64 = chain;
  recipient.CKr_b64 = chain;
  recipient.DHr_b64 = sender.DHs.pub_b64;
  const first = await encryptMessage(sender, 'Hello 😊');
  // Independent BLAKE2b-256 vector for the existing chain KDF, not generated by the tested library.
  assert.equal(Buffer.from(sodium.from_base64(sender.CKs_b64, sodium.base64_variants.ORIGINAL)).toString('hex'), 'efac2809ffcede82b700793ff1411713c94cc27d979c1136fb49bb9dde828c8d');
  const second = await encryptMessage(sender, 'Second');
  assert.equal(await decryptMessage(recipient, second.header, second.ciphertext_b64, second.nonce_b64), 'Second');
  assert.equal(await decryptMessage(recipient, first.header, first.ciphertext_b64, first.nonce_b64), 'Hello 😊');
});
