const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const cache=new Map(),draft={version:1,records:{},inbox:{},outbox:{}};
const mocks={'@/config':{apiUrl:'https://relay.invalid'},'@/lib/signal/deviceManager':{currentMessagingRuntime:()=>({vault:{atomic:async work=>work(draft)}})}};
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const module={exports:{}};const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;new Function('require','module','exports',source)(name=>name in mocks?mocks[name]:name.startsWith('@/')?load('src/'+name.slice(2)+'.ts'):name.startsWith('.')?load(path.join(path.dirname(file),name+'.ts')):require(name),module,module.exports);cache.set(file,module.exports);return module.exports;}
const {localConversation}=load('src/lib/conversations/messaging.ts'),{eventSchema,deleteSigningBytes}=load('src/lib/signal/contracts.ts'),{base64}=load('src/lib/signal/attachments.ts');
test('encrypted event projection enforces original hashes, authors, monotonic edit revisions and signed delete ownership',async()=>{
 const room=crypto.randomUUID(),device=crypto.randomUUID();const keys=await crypto.subtle.generateKey('Ed25519',true,['sign','verify']),pub=base64(new Uint8Array(await crypto.subtle.exportKey('raw',keys.publicKey)));let seq=0;
 const event=(senderId,content)=>eventSchema.parse({v:2,eventId:crypto.randomUUID(),conversationId:room,senderId,senderDeviceId:device,createdAt:new Date().toISOString(),content});
 function store(e){const id=crypto.randomUUID();draft.records[`event:${e.eventId}`]=JSON.stringify(e);draft.records[`wire:${id}`]=JSON.stringify({id,eventId:e.eventId,conversation:room,fromUserId:e.senderId,fromDeviceId:device,senderActionSigningPublic:pub,serverSequence:String(++seq),createdAt:e.createdAt,seen:[],read:[]});return id;}
 const original=event('alice',{kind:'text',text:'first'});store(original);const hash=base64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(original))))),target={targetId:original.eventId,targetHash:hash};
 store(event('bob',{kind:'edit',...target,text:'forged',revision:1}));store(event('alice',{kind:'edit',...target,text:'edited',revision:1}));store(event('alice',{kind:'edit',...target,text:'stale',revision:1}));store(event('alice',{kind:'edit',...target,text:'wrong hash',revision:2,targetHash:'A'.repeat(44)}));
 store(event('bob',{kind:'reaction',...target,emoji:'👍',remove:false}));let projected=await localConversation('alice',room,'bob');assert.equal(projected.length,1);assert.equal(projected[0].content,'edited');assert.equal(projected[0].revision,1);assert.deepEqual(projected[0].reactions,[{userId:'bob',reaction:'👍'}]);
 store(event('bob',{kind:'reaction',...target,emoji:'👍',remove:true}));store(event('alice',{kind:'delete',...target,signature:base64(new Uint8Array(64))}));projected=await localConversation('alice',room,'bob');assert.equal(projected[0].deleted,false);assert.equal(projected[0].reactions.length,0);
 const deletion=event('alice',{kind:'delete',...target,signature:''});deletion.content.signature=base64(new Uint8Array(await crypto.subtle.sign('Ed25519',keys.privateKey,deleteSigningBytes(deletion,target.targetId,target.targetHash))));store(deletion);projected=await localConversation('alice',room,'bob');assert.equal(projected[0].deleted,true);assert.equal(projected[0].content,'Message deleted');
});
