const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),React=require('react'),{JSDOM}=require('jsdom');
function load(file,mocks={}){const module={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText)(name=>name in mocks?mocks[name]:require(name),module,module.exports);return module.exports;}
const keyboard=load('src/utils/game-input.ts');
for(const name of ['AcronymBox','AnagramBox','TypeManiaBox','UnscrambleBox','WordMakerBox','ChatBox'])test(`${name}: Enter sends once without form submission or parent shortcuts; repeats, IME and Shift+Enter do not send`,async()=>{
 const dom=new JSDOM('<div id="root"></div>');global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;dom.window.HTMLElement.prototype.scrollTo=()=>{};
 let field,parentKeys=0,submits=0;const sent=[];const game={question:{id:'q1',roundId:'r1',question:'CAT',answer:'DOG'},gameRoomInfo:{gameType:'MINDMASH',catType:name},countdown:12,energy:{gauge:100,turbo:100},messages:[],gameSocketIo:{emit:(...args)=>sent.push(args)}};
 const box=({children,ref})=>React.createElement('div',{ref},children);
 const ui={Box:box,Typography:box,Stack:box,Chip:box,Fade:box,IconButton:box,Button:({children,type,onClick})=>React.createElement('button',{type,onClick},children),TextField:props=>{field=props;return React.createElement('textarea',{value:props.value,onChange:props.onChange,onKeyDown:props.onKeyDown,onKeyUp:props.onKeyUp});}};
 const Component=load(`src/components/games/${name}.tsx`,{'@/utils/game-input':keyboard,'@mui/material':ui,'@mui/icons-material/KeyboardArrowDown':{__esModule:true,default:()=>null},'@/context/SocketIoContext':{},'react-toastify':{},'@/types':{GameEventEnum:{GAME_ROOM_ANSWER:'answer'}},'@/providers/NotificationsProvider':{useNotifications:()=>({show(){}})},'@/context/GameSocketIoContext':{useGameSocketIoContext:()=>game},'./AnswersTable':{__esModule:true,default:()=>null},'./ChatBubble':{__esModule:true,default:()=>null}}).default;
 const root=require('react-dom/client').createRoot(document.getElementById('root'));
 const key=async options=>{const event=new window.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true,...options});await React.act(async()=>document.querySelector('textarea').dispatchEvent(event));return event;};
 try{
  await React.act(async()=>root.render(React.createElement('form',{onSubmit:event=>{event.preventDefault();submits++;},onKeyDown:()=>parentKeys++,onKeyUp:()=>parentKeys++},React.createElement(Component,{currentUserId:'player',hidden:false,onSendMessage:content=>sent.push(['chat',content])}))));
  document.querySelector('textarea').focus();await key();assert.equal(document.activeElement,document.querySelector('textarea'),'empty Enter keeps keyboard focus');
  await React.act(async()=>field.onChange({target:{value:'DOG'}}));const first=await key();assert.equal(first.defaultPrevented,true);assert.equal(sent.length,1);assert.equal(parentKeys,0);assert.equal(field.value,'');assert.notEqual(document.activeElement,document.querySelector('textarea'),'submitted Enter dismisses keyboard');
  if(name!=='ChatBox')assert.deepEqual(sent[0][1],{answer:'DOG'.toLowerCase()===sent[0][1].answer?'dog':'DOG',timer:12,qId:'q1',roundId:'r1',gameType:'MINDMASH',catType:name});
  document.querySelector('textarea').focus();await React.act(async()=>field.onChange({target:{value:'DOG'}}));assert.equal((await key({repeat:true})).defaultPrevented,true);assert.equal(sent.length,1);assert.equal(field.value,'DOG');
  assert.equal((await key({isComposing:true})).defaultPrevented,false);assert.equal(sent.length,1);assert.equal((await key({shiftKey:true})).defaultPrevented,false);assert.equal(sent.length,1);
  const up=new window.KeyboardEvent('keyup',{key:'Enter',bubbles:true,cancelable:true});await React.act(async()=>document.querySelector('textarea').dispatchEvent(up));assert.equal(up.defaultPrevented,true);assert.equal(parentKeys,0);assert.equal(submits,0);assert.equal(document.querySelector('button').type,'button');assert.equal(document.activeElement,document.querySelector('textarea'),'repeat, composition and Shift+Enter keep keyboard focus');
  if(name!=='ChatBox'){game.energy.gauge=0;await key();assert.equal(sent.length,1);assert.equal(document.activeElement,document.querySelector('textarea'),'blocked submission keeps keyboard focus');}
 }finally{await React.act(async()=>root.unmount());dom.window.close();}
});
