const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),React=require('react');
const {JSDOM}=require('jsdom');
test('visible accepted chat reads authenticated history and new arrivals without periodic three-second sync',async(t)=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://kwonnet.test/messages/peer/chat'});global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;document.hasFocus=()=>false;Object.defineProperty(document,'visibilityState',{value:'visible'});dom.window.HTMLElement.prototype.scrollIntoView=()=>{};
 t.mock.timers.enable({apis:['setTimeout','setInterval','Date'],now:Date.now()});
 global.IntersectionObserver=class{constructor(callback){this.callback=callback;}observe(target){this.callback([{target,isIntersecting:target.dataset.messageId==='one'}]);}disconnect(){}};
 const convo={id:'room',state:'ACCEPTED',initiator:{id:'peer'},responder:{id:'user'}};const calls=[];let syncs=0,inboxRefreshes=0;const messages=['one','two'].map(id=>({id,conversation:'room',fromUserId:'peer',content:id,seen:[],read:[],event:{eventId:id},hash:'hash'}));
 const context={messages,processed:[...messages.map(m=>({id:m.id,fromUserId:'peer',conversationId:m.conversation,action:false})),{id:'other-room-action',fromUserId:'other-peer',conversationId:'other-room',action:true}],liveReady:true,revision:0,refreshInbox:(id,totals)=>{inboxRefreshes++;assert.equal(id,'room');assert.equal(totals.unreadCount,0);},refresh:async()=>{syncs++;return {conversation:convo};},convoSocketIo:{on(){},off(){},emit(){}}};
 const ui=({children,ref,...props})=>React.createElement('div',{ref,'data-message-id':props['data-message-id']},children);
 const mocks={'@mui/material':Object.fromEntries(['Alert','Avatar','Box','Button','Dialog','DialogContent','DialogTitle','IconButton','Paper','Stack','TextField','Typography'].map(name=>[name,ui])),'@mui/icons-material':{ArrowBackIosNewOutlined:ui,AttachFile:ui,SendOutlined:ui,LockOutlined:ui},'next/link':{__esModule:true,default:ui},'next/navigation':{useRouter:()=>({})},'@/hooks':{useAuthSession:()=>({user:{id:'user'},token:'token'})},'@/context/ConvoSocketIoContext':{useConvoSocketIoContext:()=>context},'@/lib/signal/attachments':{IMAGE_TYPES:['image/png','image/jpeg','image/webp'],validateImageUploads:()=>{}},'@/lib/conversations':{},'@/lib/conversations/messaging':{sendReceiptBatch:async(...args)=>{calls.push(args);return {suppressed:false,unreadCount:0,unseenCount:0,totalUnreadMsg:0,totalUnseenMsg:0};}},'./ChatBubble':{__esModule:true,default:({message})=>React.createElement('span',null,message.content)}};
 const module={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync('src/app/(dashboard)/messages/[[...slug]]/ChatBoxClient.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText)(name=>name in mocks?mocks[name]:require(name),module,module.exports);
 const root=require('react-dom/client').createRoot(document.getElementById('root'));
 try{await React.act(async()=>root.render(React.createElement(module.exports.default,{params:{recipient:{id:'peer',name:'Peer',username:'peer'},convo}})));await React.act(async()=>t.mock.timers.tick(250));assert.equal(calls.length,1);assert.deepEqual(calls[0],['user','token','room',[],['one','two']]);assert.equal(inboxRefreshes,1,'an acknowledged receipt refreshes badges even without a socket hint');const before=syncs;await React.act(async()=>t.mock.timers.tick(3000));assert.equal(syncs,before,'the UI clock does not poll the database');assert.equal(calls.length,1,'acknowledged IDs are not resent');context.messages=context.messages.concat({...messages[0],id:'three',content:'new arrival'});context.processed=context.processed.concat({id:'three',fromUserId:'peer',conversationId:'room',action:false});await React.act(async()=>root.render(React.createElement(module.exports.default,{params:{recipient:{id:'peer',name:'Peer',username:'peer'},convo}})));await React.act(async()=>t.mock.timers.tick(250));assert.deepEqual(calls[1],['user','token','room',[],['three']]);assert.equal(inboxRefreshes,2);}
 finally{await React.act(async()=>root.unmount());dom.window.close();delete global.IntersectionObserver;t.mock.timers.reset();}
});
